version: '3'

services:
  web:
     build:
       context: .
       dockerfile: Dockerfile
     depends_on:
       - mongo
     volumes: 
       - ./:/usr/src/app
     env_file: .env
     ports:
       - '3000:3000'
     environment:
       - DOCKERIZED=true
     stdin_open: true
     tty: true
  mongo:
    image: mongo:3.0.14
    

